version: '3.8'

services:
  # Service pour MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Remplacez par un mot de passe sécurisé
      MYSQL_DATABASE: pi
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql

  # Service pour l'application Spring Boot
  back:
    image: azkhaled/back:latest  # Remplacez par l'image de votre application backend
    container_name: back
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/pi?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword  # Doit correspondre au mot de passe root de MySQL
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8088
      SERVER_SERVLET_CONTEXT_PATH: /pi
    ports:
      - "8088:8088"
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
